version: 2
jobs:
  deploy-to-master:
    working_directory: ~/paycoInfo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -qq -y python-pip libpython-dev
      - run: curl -O https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
      - run: sudo pip install -q awscli --upgrade
      - run:
          name: Setup AWS credentials
          command: |
            mkdir -p ~/.aws
            printf "[default]\nregion = ap-northeast-1\nnoutput = json" > ~/.aws/config
            printf "[default]\naws_access_key_id = ${AWS_ACCESS_KEY_ID}\naws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" > ~/.aws/credentials
            chmod 600 ~/.aws/*
      - run:
          name: deploy static files to s3 prod
          command: aws s3 sync ./payco/dist/payco s3://payco-info/ --delete
workflows:
  version: 2
  build_deploy:
    jobs:
      - deploy-to-master:
         filters:
            branches:
              only: master
      